spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true            # Formats SQL queries for readability
      hibernate.use_sql_comments: true      # Adds comments to SQL queries
      hibernate.highlight_sql: true         # Highlights SQL in logs (if supported)
      hibernate.generate_statistics: true   # Enables performance stats (optional)
      hibernate:
        hbm2ddl:
          auto: update

  logging:
    level:
      org.hibernate.SQL: debug                 # Logs SQL queries
      org.hibernate.type.descriptor.sql: trace